export const FB_ATTEMPTING = 'FB_ATTEMPTING';
export const FB_LOGIN_FAILED = 'FB_LOGIN_FAILED';
export const FB_LOGIN_SUCCESS = 'FB_LOGIN_SUCCESS';
export const REFRESH_PROFILE = 'REFRESH_PROFILE';


export const SIGNIN_ATTEMPING = 'SIGNIN_ATTEMPING';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REFRESH_USERS = 'REFRESH_USERS';


export const SIGNIN_ATTEMPING_DOCTOR = 'SIGNIN_ATTEMPING_DOCTOR';
export const SIGNUP_FAILED_DOCTOR = 'SIGNIN_SUCCESS_DOCTOR';
export const SIGNIN_SUCCESS_DOCTOR = 'LOGIN_SUCCESS_DOCTOR';


export const ORGANIZE_ATTEMPING = 'ORGANIZE_ATTEMPING';
export const ORGANIZE_FAILED = 'ORGANIZE_FAILED';
export const ORGANIZE_SUCCESS = 'ORGANIZE_SUCCESS';


export const LOCATION_ATTEMPING = 'LOCATION_ATTEMPING';
export const LOCATION_FAILED = 'LOCATION_FAILED';
export const LOCATION_SUCCESS = 'LOCATION_SUCCESS';


export const FETCH_MEETING = 'FETCH_MEETING';