export const FB_ATTEMPTING = 'FB_ATTEMPTING';
export const FB_LOGIN_FAILED = 'FB_LOGIN_FAILED';
export const FB_LOGIN_SUCCESS = 'FB_LOGIN_SUCCESS';



export const SIGNIN_ATTEMPING = 'SIGNIN_ATTEMPING';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';

